# Generated by Django 3.1.8 on 2021-11-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
